version: "2"

checks:
  argument-count:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 30
  return-statements:
    config:
      threshold: 10
  similar-code:
    config:
      threshold: 200
  identical-code:
    config:
      threshold: 200

exclude_patterns:
  - "scripts/"
  - "src/commonMain/kotlin/de/westermann/kobserve/Extensions.kt"
  - "src/commonTest/"
